#!/bin/bash
cd "$(dirname "$0")"

echo " "
echo "## INSTALL HELM v$1 ######################"

ver=$1

tar_gz=helm-v$ver-linux-amd64.tar.gz

rm -rf linux-amd64
rm -f $tar_gz

wget https://get.helm.sh/$tar_gz

tar -xvf $tar_gz

sudo cp linux-amd64/helm /usr/local/bin/helm



