#!/bin/bash
cd "$(dirname "$0")"

this_dir=$PWD

ver=$1

##set -x

url=https://nodejs.org/dist/v$ver
file=node-v$ver

if [ "$ver" == "" ]; then
  echo "ERROR: missing version # on the command line"
  exit 1
fi

echo " "  
echo "######## Installing nodejs v$ver ########"

os=`uname -s`
if [ "$os" == "Darwin" ]; then
  flavor=darwin-x64
elif [ "$os" == "Linux" ]; then
  yum --version > /dev/null 2>&1
  rc=$?
  arch=`arch`
  if [ "$rc" == "0" ] && [ "$arch" == "x86_64" ]; then
    flavor=linux-x64
  elif [ "$arch" == "aarch64" ]; then
    flavor=linux-arm64
  else
    echo "$arch is not presently support"
  fi
fi

dir=$file-$flavor
full_file=$dir.tar.xz

bindir=/usr/local/bin
sudo rm -rf $bindir/nodejs*
cd $bindir

echo " downloading $full_file from $url .."
sudo wget -q $url/$full_file
rc=$?
if [ "$rc" != "0" ]; then
  echo "ERROR: $ver not found or cannot download"
  exit 1
fi

echo " extracting $full_file ... "
sudo rm -rf $dir
sudo tar -xf $full_file
rc=$?
if [ "$rc" != "0" ]; then
  exit 1
fi

sudo mv $dir nodejs
sudo rm $full_file*

cd $this_dir
logdir="data/logs/nodejs"
mkdir -p ../$logdir

echo ""
echo "consider adding $bindir/nodejs/bin to the PATH"

if [[ "$isSTART" == "True" ]]; then
  cd ..
  ./io start nodejs
fi

echo "goodbye"
exit
