#!/bin/bash
cd "$(dirname "$0")"

ver=$1
repo=https://repo.mongodb.org/apt/ubuntu
list=/etc/apt/sources.list.d/mongodb-org-$ver.list

echo " "
echo "## INSTALL MONGODB $ver #########################################"

if [ "$ver" == "" ]; then
  echo "ERROR: version must be supplied"
  exit 1
fi

set -x

sudo apt-get install -y gnupg
wget -qO - https://www.mongodb.org/static/pgp/server-$ver.asc | sudo apt-key add -
rc=$?
if [ ! "$rc" == "0" ]; then
  echo "ERROR: $ver is an invalid mongo version"
  exit 1
fi

echo "deb [ arch=amd64,arm64 ] $repo focal/mongodb-org/$ver multiverse" | sudo tee $list
sudo apt-get update -y

sudo apt-get install -y mongodb-org

sudo systemctl daemon-reload
sudo systemctl start mongod

sudo systemctl status mongod --no-pager
