
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "038a6880368cc63470678d60bcd2efba5f8b3bbb",
 "version": "1.10.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
