#!/bin/bash
cd "$(dirname "$0")"

echo " "
echo "## INSTALL REDIS ##########################################"
source getPKMG.sh


if [ "$PKMG" == "yum" ]; then
  echo "not supported on EL"
  exit 1
else
  sudo add-apt-repository -y ppa:redislabs/redis
  sudo apt-get -y update
  sudo apt install -y  redis-server
  sudo cp redis.conf /etc/redis/.
  sudo systemctl restart redis-server
fi
