#!/bin/bash
cd "$(dirname "$0")"

sudo apt remove -y docker docker-engine docker.io containerd runc > /dev/null 2>&1
sudo apt install -y apt-transport-https ca-certificates curl \
  gnupg-agent software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt update
sudo apt install -y docker-ce docker-ce-cli containerd.io

sudo systemctl enable docker
sudo systemctl start docker
sudo usermod -aG docker $USER

exit 0
