#!/bin/bash
cd "$(dirname "$0")"

##set -x

cp pgcat.toml.template pgcat.toml

if [ "$pgeUser" == "" ]; then
  usr=$USER
else
  usr="$pgeUser"
fi

if [ "$pgePasswd" == "" ]; then
  passwd=`head -1 ~/.pgpass | cut -d':' -f 5`
else
  passwd="$pgePasswd"
fi

if [ "$pgName" == "" ]; then
  db=postgres
else
  db="$pgName"
fi

sed -i -e "s/USR/$usr/g"       pgcat.toml
sed -i -e "s/PASSWD/$passwd/g" pgcat.toml
sed -i -e "s/DB/$db/g"         pgcat.toml

if [ "$isAutoStart" == "True" ]; then
  cd ..
  ./nc start cat
fi

