#!/bin/bash
cd "$(dirname "$0")"

##set -x

now=`date '+%Y-%m-%d_%H:%M:%S'`

echo "" >> pgcat.log
echo "pgcat starting"

killall -q pgcat | tee -a pgcat.log

echo "$now - starting pgcat" >> pgcat.log

./pgcat -d pgcat.toml >> pgcat.log 2>&1  &
