#!/bin/bash
cd "$(dirname "$0")"

if [ "$pgePort" == "" ]; then
  port=5432
else
  port=$pgePort
fi

if [ "$pgName" == "" ]; then
  db=postgres
else
  db=$pgName
fi

echo " creating default file postgrest.conf:"
cat << EOF > postgrest.conf
db-uri = "postgres://localhost:$port/$db"
db-schemas = "public"
EOF
#cat postgrest.conf

cd ..
./nc init postgrest
./nc start postgrest

##sudo dnf module reset nodejs -y

##sudo dnf module install nodejs:18 -y
##sudo npm install -g swagger-ui-dist
##sudo npm install -g http-server

##hostname=`hostname`
##cp init-swagger-initializer.js swagger-initializer.js
##sed -i "s/localhost/$hostname/" swagger-initializer.js
##sudo cp swagger-initializer.js /usr/local/lib/node_modules/swagger-ui-dist/.

