# create new
FROM debian
MAINTAINER pgEdge <support@pgedge.com>

RUN apt-get update
RUN apt-get -y install wget gawk gcc
#RUN echo "Dockerfile Test on Apache2" > /var/www/html/index.html

EXPOSE 5432
#CMD ["/usr/sbin/apachectl", "-D", "FOREGROUND"]
