#!/bin/bash
cd "$(dirname "$0")"


install="sudo dnf install -y"
sysctl="sudo systemctl"
fcmd="sudo firewall-cmd"

rpm=pgadmin4-redhat-repo-2-1.noarch.rpm
url=https://ftp.postgresql.org/pub/pgadmin/pgadmin4/yum

set -x

$install httpd
$sysctl start httpd
$sysctl enable httpd
$sysctl status httpd -l --no-pager

firewall-cmd --help
rc=$?
if [ "$rc" == "0" ]; then
  $fcmd --permanent --add-port=80/tcp --zone=external
  $fcmd --permanent --add-port=443/tcp --zone=external
fi


sudo rpm -i $url/$rpm

$install pgadmin4-web

sudo /usr/pgadmin4/bin/setup-web.sh --yes

