#!/bin/bash
cd "$(dirname "$0")"

set -x

rpm=pgadmin4-redhat-repo-1-1.noarch.rpm
url=https://ftp.postgresql.org/pub/pgadmin/pgadmin4

sudo rpm -i --force $url/yum/$rpm
sudo yum install -y pgadmin4-web

