#!/bin/bash
cd "$(dirname "$0")"

pgeV=pg15

echo " "
echo "## Install PgEdge for $pgeV  #######################################"

cd ..

./nc install $pgeV --start 
./nc install install spock-$pgeV : tune : install postgrest

