#!/bin/bash
cd "$(dirname "$0")"

echo " "
echo "## Remove pgedge $pgN ###########################################"

cd ..

./nc remove pg$pgN

if [ -d "postgrest" ]; then
  ./nc remove postgrest
fi

if [ -d "backrest" ]; then
  ./nc remove backrest
fi

if [ -d "bouncer" ]; then
  ./nc remove bouncer
fi 

