#!/bin/bash
cd "$(dirname "$0")"

ver=15

echo " "
echo "## Remove pgEdge $ver ###########################################"

cd ..

./nc remove pg$ver

if [ -d "postgrest" ]; then
  ./nc remove postgrest
fi

if [ -d "backrest" ]; then
  ./nc remove backrest
fi

if [ -d "bouncer" ]; then
  ./nc remove bouncer
fi 

