#!/bin/bash
cd "$(dirname "$0")"

rm -rf lib
rm -rf share

thisDir=$PWD

sudo cp bin/pgbackrest  /usr/bin
sudo chmod 755 /usr/bin/pgbackrest

sudo mkdir -p -m 770 /var/log/pgbackrest
sudo chown $USER:$USER /var/log/pgbackrest
sudo mkdir -p /etc/pgbackrest
sudo mkdir -p /etc/pgbackrest/conf.d
sudo touch /etc/pgbackrest/pgbackrest.conf
sudo chmod 640 /etc/pgbackrest/pgbackrest.conf
sudo chown $USER:$USER /etc/pgbackrest/pgbackrest.conf

sudo mkdir -p /var/lib/pgbackrest
sudo chmod 750 /var/lib/pgbackrest
sudo chown $USER:$USER /var/lib/pgbackrest

cd ../data
dataDir=$PWD
pgV=`ls -d pg?? | head -1`
sed -i -e "s!pg1-path=xx!pg1-path=$dataDir/$pgV!g" $thisDir/pgbackrest.conf 

myCipher=`dd if=/dev/urandom bs=256 count=1 2> /dev/null | LC_ALL=C tr -dc 'A-Za-z0-9' | head -c32`
sed -i -e "s/repo1-cipher-pass=xx/repo1-cipher-pass=$myCipher/g" $thisDir/pgbackrest.conf 

cp $thisDir/pgbackrest.conf /etc/pgbackrest/pgbackrest.conf

