FROM rockylinux:9.2
COPY docker-entrypoint.sh /
RUN dnf -y --allowerasing install epel-release  \
    curl sudo procps vim unzip python3   \
    openssh-server openssh-clients dnsutils

RUN useradd -m pgedge -s /bin/bash
RUN echo pgedge:asdf | chpasswd
RUN echo "pgedge ALL = NOPASSWD: ALL" >/etc/sudoers.d/pgedge
COPY fake-systemctl /usr/local/bin/systemctl
CMD ./docker-entrypoint.sh
