FROM rockylinux:8

LABEL maintainer="OSCG-IO team"

SHELL ["/bin/bash", "-c"]

USER root

RUN dnf update -y \
    && dnf install -y wget curl git sudo python39 python39-devel \
    && dnf clean all \
    && rm -rf /var/cache/yum

CMD /bin/bash
