FROM rockylinux:9.2
RUN yum install curl sudo procps vim unzip -y --allowerasing
RUN yum install python3 -y
RUN yum install openssh-server openssh-clients dnsutils -y
RUN useradd -m pgedge -s /bin/bash
RUN echo pgedge:asdf |chpasswd
RUN echo "pgedge ALL = NOPASSWD: ALL" >/etc/sudoers.d/pgedge
COPY pgedgekey.zip /home/pgedge/
COPY fake-systemctl /usr/local/bin/systemctl
COPY bootstrap.sh /usr/local/bin/
COPY forever.sh /usr/local/bin/
ENTRYPOINT /usr/local/bin/forever.sh
