FROM rockylinux:8

LABEL maintainer="OSCG-IO team"

SHELL ["/bin/bash", "-c"]

USER root

RUN dnf update -y \
    && dnf install -y wget curl git sudo python39 python39-devel \
    && dnf clean all \
    && rm -rf /var/cache/yum

RUN useradd oscg -U -m -d /opt/oscg \
    && echo "%oscg ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers

USER oscg
WORKDIR /opt/oscg

RUN git clone https://github.com/oscg-io/io
WORKDIR io
RUN ./setupInitial.sh \
    && dnf clean all \
    && rm -rf /var/cache/yum

CMD /bin/bash
