#!/bin/bash
cd "$(dirname "$0")"

platf="unsupported"
if [ `uname` == "Linux" ]; then
  if [ -f "/etc/redhat-release" ]; then
    if [ `arch` == "aarch64" ]; then
      platf=el9-arm
    else
      platf=el9-amd
    fi
  else
    if [ -f "/etc/os-release" ] && [ `arch` == "x86_64" ]; then
      grep "22.04" /etc/os-release > /dev/null 2>&1
      rc=$?
      if [ $rc == "0" ]; then
        platf=ubu22-amd
      fi
    fi
  fi
elif [ `uname` == "Darwin" ]; then
  platf=osx
fi

echo "platf=$platf"
if [ "$platf" == "unsupported" ]; then
  echo "unsupported platform"
  exit 1
fi

repo=`../nc get GLOBAL REPO`
file=nclibs-$platf.tar.bz2

rm -rf $file

set -x 

wget $repo/$file

dir=../hub/scripts/lib

mv $file $dir/.

cd $dir

rm -r $platf
tar -xf $file

rm $file

exit 0

