#!/bin/bash
cd "$(dirname "$0")"

platf="unsupported"
if [ `uname` == "Linux" ]; then
  if [ -f "/etc/redhat-release" ]; then
    if [ `arch` == "aarch64" ]; then
      platf=el9-arm
    else
      platf=el9-amd
    fi
  else
    if [ -f "/etc/os-release" ] && [ `arch` == "x86_64" ]; then
      grep "22.04" /etc/os-release > /dev/null 2>&1
      rc=$?
      if [ $rc == "0" ]; then
        platf=ubu22-amd
      fi
    fi
  fi
elif [ `uname` == "Darwin" ]; then
  platf=osx
fi


