#!/bin/bash
cd "$(dirname "$0")"

echo " "
echo "## Remove pgedge ################################################"

cd ..

if [ -d "pg16" ]; then
  ./pgedge remove pg16
fi

if [ -d "pg15" ]; then
  ./pgedge remove pg15
fi

if [ -d "pg14" ]; then
  ./pgedge remove pg14
fi

if [ -d "postgrest" ]; then
  ./pgedge remove postgrest
fi

if [ -d "backrest" ]; then
  ./pgedge remove backrest
fi

if [ -d "pgcat" ]; then
  ./pgedge remove pgcat
fi 

