#!/bin/bash
cd "$(dirname "$0")"

ver=7.x
repo="https://artifacts.elastic.co/packages/$ver/apt stable main"
list=/etc/apt/sources.list.d/elastic-$ver.list

echo " "
echo "## INSTALL ELASTICSEARCH $ver #################################"

set -x

wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
echo "deb $repo" | sudo tee $list

sudo apt-get update
sudo apt-get install -y elasticsearch

sudo systemctl daemon-reload
sudo systemctl enable elasticsearch

sudo systemctl status elasticsearch --no-pager

