#!/bin/bash
cd "$(dirname "$0")"

sudo rm -rf /usr/local/patroni
sudo mkdir /usr/local/patroni
sudo cp -rf *  /usr/local/patroni/

/usr/local/patroni/patroni.py --version
/usr/local/patroni/patronictl.py version

sudo cp patroni.service /etc/systemd/system/.
sudo systemctl daemon-reload
sudo systemctl enable patroni
sudo systemctl start  patroni
