#!/bin/bash
cd "$(dirname "$0")"

echo " "
echo "## INSTALL PATRONI ##############################################"
source getPKMG.sh

## DEB #########################################################
sudo apt update -y
sudo apt install -y etcd haproxy

sudo pip3 install -r requirements.txt
sudo pip3 install psycopg2-binary
python3 setup.py build
sudo python3 setup.py install

