#!/bin/bash
cd "$(dirname "$0")"

LOCAL_BIN=$HOME/.local/bin
PATRONI_CONF=/usr/patroni/conf
PGDATA=$MY_HOME/data/pg15

source getPKMG.sh

if [ ! "$PLATFORM" == "el8" ] && [ ! "$PLATFORM" == "el9" ] ; then
  echo "ERROR: platform $PLATFORM is not supported ( only el8/9 is supported)"
  exit 1
fi

set -x

echo ""
echo "## Install HA Proxy..."
sudo yum install -y haproxy wget

echo ""
echo "## Upgrading pip3 to latest"
pip3 install --upgrade pip

echo ""
echo "## Installing Patroni & it's dependencies..."
pip3 install psycopg psycopg-binary patroni[etcd] --user
sudo cp $LOCAL_BIN/patroni /usr/local/bin/.

echo ""
if [ -f $PGDATA/server.key ]; then
  echo "## Copying Certs for Patroni..."
  sudo mkdir -p $PATRONI_CONF
  sudo cp $PGDATA/server.* $PATRONI_CONF/.
else
  echo "## No pg15 instance to configure for patroni"
  exit 0
fi

exit 0

