#!/bin/bash
cd "$(dirname "$0")"

source ./getPKMG.sh

echo "# installing autossh"

if [ "$PKMG" == "yum" ]; then
  sudo yum install -y autossh
elif [ "$PKMG" == "apt" ]; then
  sudo apt install -y autossh
elif [ "$PKMG" == "brew" ]; then
  brew install autossh
else
  echo "Package Manager \'$PKMG\' not supported"
  exit 1
fi

